# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='joined_trips', to='log_reg.User'),
        ),
    ]
